In [1]:
#importing pandas, matplotlib, and seaborn
import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
#importing the datasets

df_orders = pd.read_csv(r"C:\Users\DELL\Downloads\orders.csv")
df_order_details = pd.read_csv(r"C:\Users\DELL\Downloads\order_details.csv")
df_pizzas = pd.read_csv(r"C:\Users\DELL\Downloads\pizzas.csv")
df_pizza_types = pd.read_csv(r"C:\Users\DELL\Downloads\pizza_types.csv", encoding="latin1")

In [3]:
#joining df_order_details and df_orders
df_orders_full = pd.merge(
    df_order_details,
    df_orders,
    on="order_id",
    how="inner")

In [4]:
#joining df_orders_full and df_pizzas
df_orders_pizzas = pd.merge(
    df_orders_full,
    df_pizzas,
    on="pizza_id",
    how="inner")

In [5]:
#joining all tables together

final_df = pd.merge(
    df_orders_pizzas,
    df_pizza_types,
    on="pizza_type_id",
    how="inner")

In [6]:
final_df.head()

,order_details_id,order_id,pizza_id,quantity,date,time,pizza_type_id,size,price,name,category,ingredients
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese"
1,179,77,hawaiian_m,1,2015-01-02,12:22:46,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese"
2,357,146,hawaiian_m,1,2015-01-03,14:22:10,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese"
3,389,163,hawaiian_m,1,2015-01-03,16:54:54,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese"
4,568,247,hawaiian_m,1,2015-01-04,20:55:29,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese"

In [7]:
final_df.tail()

,order_details_id,order_id,pizza_id,quantity,date,time,pizza_type_id,size,price,name,category,ingredients
48615,48176,21167,brie_carre_s,1,2015-12-27,17:39:57,brie_carre,S,23.65,The Brie Carre Pizza,Supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni..."
48616,48244,21198,brie_carre_s,1,2015-12-28,15:39:02,brie_carre,S,23.65,The Brie Carre Pizza,Supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni..."
48617,48311,21225,brie_carre_s,1,2015-12-29,13:20:17,brie_carre,S,23.65,The Brie Carre Pizza,Supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni..."
48618,48456,21282,brie_carre_s,1,2015-12-31,12:09:59,brie_carre,S,23.65,The Brie Carre Pizza,Supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni..."
48619,48527,21308,brie_carre_s,1,2015-12-31,16:44:35,brie_carre,S,23.65,The Brie Carre Pizza,Supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni..."

In [8]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  object
 3   quantity          48620 non-null  int64
 4   date              48620 non-null  object
 5   time              48620 non-null  object
 6   pizza_type_id     48620 non-null  object
 7   size              48620 non-null  object
 8   price             48620 non-null  float64
 9   name              48620 non-null  object
 10  category          48620 non-null  object
 11  ingredients       48620 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.5+ MB

In [9]:
final_df.shape

(48620, 12)

In [10]:
final_df.isnull().sum()

order_details_id    0
order_id            0
pizza_id            0
quantity            0
date                0
time                0
pizza_type_id       0
size                0
price               0
name                0
category            0
ingredients         0
dtype: int64

In [11]:
final_df["date"].value_counts()

date
2015-11-26    261
2015-11-27    259
2015-10-15    258
2015-07-04    233
2015-07-03    207
             ...
2015-12-27     87
2015-11-22     82
2015-12-29     77
2015-03-22     76
2015-12-30     73
Name: count, Length: 358, dtype: int64

In [12]:
final_df["date"] = pd.to_datetime(final_df["date"])

In [13]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  object
 3   quantity          48620 non-null  int64
 4   date              48620 non-null  datetime64[ns]
 5   time              48620 non-null  object
 6   pizza_type_id     48620 non-null  object
 7   size              48620 non-null  object
 8   price             48620 non-null  float64
 9   name              48620 non-null  object
 10  category          48620 non-null  object
 11  ingredients       48620 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(3), object(7)
memory usage: 4.5+ MB

In [14]:
final_df["time"] = pd.to_datetime(final_df["time"])

In [15]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  object
 3   quantity          48620 non-null  int64
 4   date              48620 non-null  datetime64[ns]
 5   time              48620 non-null  datetime64[ns]
 6   pizza_type_id     48620 non-null  object
 7   size              48620 non-null  object
 8   price             48620 non-null  float64
 9   name              48620 non-null  object
 10  category          48620 non-null  object
 11  ingredients       48620 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(3), object(6)
memory usage: 4.5+ MB

 What is the total revenue/sales?

In [16]:
# checking the columns of the dataset
final_df.columns

Index(['order_details_id', 'order_id', 'pizza_id', 'quantity', 'date', 'time',
       'pizza_type_id', 'size', 'price', 'name', 'category', 'ingredients'],
      dtype='object')

In [17]:
# create a revenue column

final_df["revenue"] = final_df["quantity"] * final_df["price"]

In [18]:
# calculate the total revenue
total_revenue = final_df["revenue"].sum()
total_revenue

817860.05

In [19]:
print(f"The Total Revenue is: {total_revenue:,.2f}")

The Total Revenue is: 817,860.05

### I calculated total revenue by multiplying quantity ordered by unit price for each order, then aggregating across all transactions using pandas.

In [20]:
#revenue by pizza
revenue_by_pizza = (
    final_df
    .groupby("name")["revenue"]
    .sum()
    .sort_values(ascending=False))

In [21]:
#revenue by category
revenue_by_category = (
    final_df
    .groupby("category")["revenue"]
    .sum())

In [22]:
#revenue by date
revenue_by_date = (
    final_df
    .groupby("date")["revenue"]
    .sum())

In [23]:
final_df.head()

,order_details_id,order_id,pizza_id,quantity,date,time,pizza_type_id,size,price,name,category,ingredients,revenue
0,1,1,hawaiian_m,1,2015-01-01,2026-02-10 11:38:36,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",13.25
1,179,77,hawaiian_m,1,2015-01-02,2026-02-10 12:22:46,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",13.25
2,357,146,hawaiian_m,1,2015-01-03,2026-02-10 14:22:10,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",13.25
3,389,163,hawaiian_m,1,2015-01-03,2026-02-10 16:54:54,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",13.25
4,568,247,hawaiian_m,1,2015-01-04,2026-02-10 20:55:29,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",13.25

In [24]:
final_df.tail()

,order_details_id,order_id,pizza_id,quantity,date,time,pizza_type_id,size,price,name,category,ingredients,revenue
48615,48176,21167,brie_carre_s,1,2015-12-27,2026-02-10 17:39:57,brie_carre,S,23.65,The Brie Carre Pizza,Supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni...",23.65
48616,48244,21198,brie_carre_s,1,2015-12-28,2026-02-10 15:39:02,brie_carre,S,23.65,The Brie Carre Pizza,Supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni...",23.65
48617,48311,21225,brie_carre_s,1,2015-12-29,2026-02-10 13:20:17,brie_carre,S,23.65,The Brie Carre Pizza,Supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni...",23.65
48618,48456,21282,brie_carre_s,1,2015-12-31,2026-02-10 12:09:59,brie_carre,S,23.65,The Brie Carre Pizza,Supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni...",23.65
48619,48527,21308,brie_carre_s,1,2015-12-31,2026-02-10 16:44:35,brie_carre,S,23.65,The Brie Carre Pizza,Supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni...",23.65

In [25]:
# Find the total quantity sold
total_quantity_sold = final_df["quantity"].sum()
total_quantity_sold

49574

In [26]:
print(f"The Total Quantity Sold: {total_quantity_sold:}")

The Total Quantity Sold: 49574

## I calculated total quantity sold by aggregating the quantity field across all transactions after joining the datasets

In [27]:
# Find the total orders
total_orders = final_df["order_id"].nunique()
total_orders

21350

In [28]:
print(f"The Total Orders: {total_orders:}")

The Total Orders: 21350

## I calculated total orders by counting the number of unique order IDs in the dataset.

In [29]:
# How many pizza types do they sell?
total_pizza_types = final_df["pizza_type_id"].nunique()
total_pizza_types

32

In [30]:
print(f"The Total Number of Pizza Types Sold Is: {total_pizza_types:}")

The Total Number of Pizza Types Sold Is: 32

## I identified the number of pizza types by counting the unique pizza type IDs in the dataset.

In [31]:
# the names of the pizza types
final_df["name"].unique()

array(['The Hawaiian Pizza', 'The Classic Deluxe Pizza',
       'The Five Cheese Pizza', 'The Italian Supreme Pizza',
       'The Mexicana Pizza', 'The Thai Chicken Pizza',
       'The Prosciutto and Arugula Pizza', 'The Barbecue Chicken Pizza',
       'The Greek Pizza', 'The Spinach Supreme Pizza',
       'The Green Garden Pizza', 'The Italian Capocollo Pizza',
       'The Spicy Italian Pizza', 'The Spinach Pesto Pizza',
       'The Vegetables + Vegetables Pizza', 'The Southwest Chicken Pizza',
       'The California Chicken Pizza', 'The Pepperoni Pizza',
       'The Chicken Pesto Pizza', 'The Big Meat Pizza',
       'The Soppressata Pizza', 'The Four Cheese Pizza',
       'The Napolitana Pizza', 'The Calabrese Pizza',
       'The Italian Vegetables Pizza', 'The Mediterranean Pizza',
       'The Pepper Salami Pizza', 'The Spinach and Feta Pizza',
       'The Sicilian Pizza', 'The Chicken Alfredo Pizza',
       'The Pepperoni, Mushroom, and Peppers Pizza',
       'The Brie Carre Pizza'], dtype=object)

In [32]:
average_pizza_price = final_df["price"].mean()
average_pizza_price

16.494132044426163

## I calculated the average pizza price using the unique pizza records to avoid duplication from multiple orders.

In [33]:
#Find the average price of the pizzas.
average_pizza_price = (
    final_df[["pizza_id", "price"]]
    .drop_duplicates()
    ["price"]
    .mean()
)
average_pizza_price

16.506043956043957

In [34]:
print(f"The Average Pizza Price is: {average_pizza_price:.2f}")

The Average Pizza Price is: 16.51

In [35]:
# What are the peak hours of sales?
final_df["hour"] = final_df["time"].dt.hour

In [36]:
# extracting the peak hours by number of orders
orders_by_hour = (
    final_df
    .groupby("hour")["order_id"]
    .nunique()
    .sort_values(ascending=False)
)

orders_by_hour

hour
12    2520
13    2455
18    2399
17    2336
19    2009
16    1920
20    1642
14    1472
15    1468
11    1231
21    1198
22     663
23      28
10       8
9        1
Name: order_id, dtype: int64

## I identified peak sales hours by extracting the hour from order time and aggregating total orders and revenue per hour.

In [37]:
final_df.head()

,order_details_id,order_id,pizza_id,quantity,date,time,pizza_type_id,size,price,name,category,ingredients,revenue,hour
0,1,1,hawaiian_m,1,2015-01-01,2026-02-10 11:38:36,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",13.25,11
1,179,77,hawaiian_m,1,2015-01-02,2026-02-10 12:22:46,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",13.25,12
2,357,146,hawaiian_m,1,2015-01-03,2026-02-10 14:22:10,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",13.25,14
3,389,163,hawaiian_m,1,2015-01-03,2026-02-10 16:54:54,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",13.25,16
4,568,247,hawaiian_m,1,2015-01-04,2026-02-10 20:55:29,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",13.25,20

In [38]:
# What are the peak hours of sales?
print(f"The Lunch Peak Hour of Sales is: 12pm - 4pm")
print(f"The Dinner Peak Hour of Sales is: 6pm - 8pm")

The Lunch Peak Hour of Sales is: 12pm - 4pm
The Dinner Peak Hour of Sales is: 6pm - 8pm

In [39]:
# Extract the day of the week
final_df["day_of_week"] = final_df["date"].dt.day_name()

In [40]:
# Find the total sales made on each day of the week. 
sales_by_day = (
    final_df
    .groupby("day_of_week")["revenue"]
    .sum()
    .sort_values(ascending=False))


sales_by_day

day_of_week
Friday       136073.90
Thursday     123528.50
Saturday     123182.40
Wednesday    114408.40
Tuesday      114133.80
Monday       107329.55
Sunday        99203.50
Name: revenue, dtype: float64

In [41]:

days_order = [
    "Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday", "Sunday"
]

sales_by_day = sales_by_day.reindex(days_order)
sales_by_day

day_of_week
Monday       107329.55
Tuesday      114133.80
Wednesday    114408.40
Thursday     123528.50
Friday       136073.90
Saturday     123182.40
Sunday        99203.50
Name: revenue, dtype: float64

## I calculated total sales by day of the week by extracting weekday names from order dates and aggregating revenue. The highest sales were recorded on [top_sales_day].

In [42]:
# Which day of the week is when sales are made the most?
top_sales_day = sales_by_day.idxmax()
top_sales_value = sales_by_day.max()

top_sales_day, top_sales_value

('Friday', 136073.9)

In [43]:
print(f"The Highest Sales Day of The Week Is: {top_sales_day:}, {top_sales_value}")

The Highest Sales Day of The Week Is: Friday, 136073.9

In [44]:
# the top 5 bestselling pizzas grouped by name, category, and quantity
top_5_pizzas_details = (
    final_df
    .groupby(["name", "category"])["quantity"]
    .sum()
    .sort_values(ascending=False)
    .head(5))


top_5_pizzas_details

name                        category
The Classic Deluxe Pizza    Classic     2453
The Barbecue Chicken Pizza  Chicken     2432
The Hawaiian Pizza          Classic     2422
The Pepperoni Pizza         Classic     2418
The Thai Chicken Pizza      Chicken     2371
Name: quantity, dtype: int64

In [45]:

top_5_pizzas = (
    final_df
    .groupby("name")["quantity"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

name
The Classic Deluxe Pizza      2453
The Barbecue Chicken Pizza    2432
The Hawaiian Pizza            2422
The Pepperoni Pizza           2418
The Thai Chicken Pizza        2371
Name: quantity, dtype: int64

## I identified the top 5 bestselling pizzas by aggregating total quantities sold per pizza and ranking them in descending order.

In [46]:
# the top 5 bestselling pizzas grouped by name, and revenue
top_5_by_revenue = (
    final_df
    .groupby("name")["revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(5))


top_5_by_revenue

name
The Thai Chicken Pizza          43434.25
The Barbecue Chicken Pizza      42768.00
The California Chicken Pizza    41409.50
The Classic Deluxe Pizza        38180.50
The Spicy Italian Pizza         34831.25
Name: revenue, dtype: float64

In [47]:
print(f"The Top 5 best selling pizzas are: {top_5_pizzas}")

The Top 5 best selling pizzas are: name
The Classic Deluxe Pizza      2453
The Barbecue Chicken Pizza    2432
The Hawaiian Pizza            2422
The Pepperoni Pizza           2418
The Thai Chicken Pizza        2371
Name: quantity, dtype: int64

In [48]:
# Extract month (year + month)
final_df["year_month"] = final_df["date"].dt.to_period("M")

In [49]:
# Calculate sales per month

monthly_sales = (
    final_df
    .groupby("year_month")["revenue"]
    .sum()
    .sort_index())

monthly_sales

year_month
2015-01    69793.30
2015-02    65159.60
2015-03    70397.10
2015-04    68736.80
2015-05    71402.75
2015-06    68230.20
2015-07    72557.90
2015-08    68278.25
2015-09    64180.05
2015-10    64027.60
2015-11    70395.35
2015-12    64701.15
Freq: M, Name: revenue, dtype: float64

## Monthly sales show noticeable fluctuations, with peak sales occurring in months of July, May, March, and October, suggesting seasonality in customer demand

In [50]:
monthly_sales_df = monthly_sales.reset_index()
monthly_sales_df["year_month"] = monthly_sales_df["year_month"].astype(str)
monthly_sales_df

   year_month   revenue
0     2015-01  69793.30
1     2015-02  65159.60
2     2015-03  70397.10
3     2015-04  68736.80
4     2015-05  71402.75
5     2015-06  68230.20
6     2015-07  72557.90
7     2015-08  68278.25
8     2015-09  64180.05
9     2015-10  64027.60
10    2015-11  70395.35
11    2015-12  64701.15

In [51]:
# Total quantity sold per pizza

pizza_performance = (
    final_df
    .groupby("name")["quantity"]
    .sum()
    .sort_values())


pizza_performance

name
The Brie Carre Pizza                           490
The Mediterranean Pizza                        934
The Calabrese Pizza                            937
The Spinach Supreme Pizza                      950
The Soppressata Pizza                          961
The Spinach Pesto Pizza                        970
The Chicken Pesto Pizza                        973
The Italian Vegetables Pizza                   981
The Chicken Alfredo Pizza                      987
The Green Garden Pizza                         997
The Pepperoni, Mushroom, and Peppers Pizza    1359
The Five Cheese Pizza                         1409
The Greek Pizza                               1420
The Italian Capocollo Pizza                   1438
The Pepper Salami Pizza                       1446
The Spinach and Feta Pizza                    1446
The Prosciutto and Arugula Pizza              1457
The Napolitana Pizza                          1464
The Mexicana Pizza                            1484
The Vegetables + Vegetables Pizza             1526
The Italian Supreme Pizza                     1884
The Four Cheese Pizza                         1902
The Big Meat Pizza                            1914
The Southwest Chicken Pizza                   1917
The Spicy Italian Pizza                       1924
The Sicilian Pizza                            1938
The California Chicken Pizza                  2370
The Thai Chicken Pizza                        2371
The Pepperoni Pizza                           2418
The Hawaiian Pizza                            2422
The Barbecue Chicken Pizza                    2432
The Classic Deluxe Pizza                      2453
Name: quantity, dtype: int64

In [52]:
# Identify pizzas that are not doing well

low_performing_pizzas = pizza_performance.head(10)
low_performing_pizzas

name
The Brie Carre Pizza            490
The Mediterranean Pizza         934
The Calabrese Pizza             937
The Spinach Supreme Pizza       950
The Soppressata Pizza           961
The Spinach Pesto Pizza         970
The Chicken Pesto Pizza         973
The Italian Vegetables Pizza    981
The Chicken Alfredo Pizza       987
The Green Garden Pizza          997
Name: quantity, dtype: int64

In [54]:
print(f"The Pizzas That Are Not Doing Well On The Menu are: {low_performing_pizzas}")

The Pizzas That Are Not Doing Well On The Menu are: name
The Brie Carre Pizza            490
The Mediterranean Pizza         934
The Calabrese Pizza             937
The Spinach Supreme Pizza       950
The Soppressata Pizza           961
The Spinach Pesto Pizza         970
The Chicken Pesto Pizza         973
The Italian Vegetables Pizza    981
The Chicken Alfredo Pizza       987
The Green Garden Pizza          997
Name: quantity, dtype: int64

In [55]:
# Identify pizzas that are not doing well be their revenue

low_revenue_pizzas = (
    final_df
    .groupby("name")["revenue"]
    .sum()
    .sort_values()
    .head(10))


low_revenue_pizzas

name
The Brie Carre Pizza            11588.50
The Green Garden Pizza          13955.75
The Spinach Supreme Pizza       15277.75
The Mediterranean Pizza         15360.50
The Spinach Pesto Pizza         15596.00
The Calabrese Pizza             15934.25
The Italian Vegetables Pizza    16019.25
The Soppressata Pizza           16425.75
The Chicken Pesto Pizza         16701.75
The Chicken Alfredo Pizza       16900.25
Name: revenue, dtype: float64

In [56]:
# combine the pizzas that are not doing well by thier total_revenue and total_quantity
pizza_summary = (
    final_df
    .groupby("name")
    .agg(
        total_quantity=("quantity", "sum"),
        total_revenue=("revenue", "sum")
    )
    .sort_values("total_quantity"))

pizza_summary.head(10)

                              total_quantity  total_revenue
name
The Brie Carre Pizza                     490       11588.50
The Mediterranean Pizza                  934       15360.50
The Calabrese Pizza                      937       15934.25
The Spinach Supreme Pizza                950       15277.75
The Soppressata Pizza                    961       16425.75
The Spinach Pesto Pizza                  970       15596.00
The Chicken Pesto Pizza                  973       16701.75
The Italian Vegetables Pizza             981       16019.25
The Chicken Alfredo Pizza                987       16900.25
The Green Garden Pizza                   997       13955.75

## Yes, there are pizza types on the menu that are underperforming. These pizzas consistently record low sales volume and revenue, indicating weak customer demand. This insight suggests opportunities for menu optimization, promotions, or possible removal.